Replace data to json files, created table with ag grid
Olia1406/studio-space pull request #6
Opened 2021-11-03 18:22 UTC by Olia1406

2021-11-04 17:27 UTC, nazarb-eagle requested changes

2021-11-04 17:27 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/data.interface.ts
> +    benchmarks: Array<any>,
Тут я думаю ти тип можеш зробити конкретний по бенчмарку

2021-11-04 17:27 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/data.interface.ts
> +    periods: Array<any>
так само тут, трохи ліниво не зробити тип)

2021-11-04 17:27 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/rank-sheets.component.ts
> +    this.rankSheetList = this.dataService.rankSheetList;
тут воно не має значення, але краще копіювати ліст, бо ти можеш внести зміни в оригінальний, що може щось поламати

2021-11-04 17:27 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/rank-sheets.component.html
> +          </ng-container>
тобі тут не потрібно контейнера, можеш ngFor прямо на компоненті писати

2021-11-04 17:27 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +  @ViewChild("agGrid", { static: false }) agGrid: AgGridAngular | any;
`AgGridAngular | any` не дуже має сенс, бо тут так чи інакше любий тип можна буде запхати. А просто `AgGridAngular` не пасує?

2021-11-04 17:27 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +  rankSheetData: any;
В тебе є клас `MobiusData`. Можна його тут використати

2021-11-04 17:27 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +  selectedDataStringPresentation: string = '';
якщо ти присвоюєш стрінгу, то не треба вказувати тип - тайпскріпт сам догадається. Лінтери (штуки, які перевіряють стиль коду) можуть навіть на таке сваритися

2021-11-04 17:27 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +  columnDefs: any = [
так само тут - вказувати тип any нема сенсу

2021-11-04 17:27 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +    return `rgb(${o(r() * s)}, ${o(r() * s)}, ${o(r() * s)})`;
нащо ти присвоїла змінним Math функції?

2021-11-04 17:27 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.html
> +    <div class="selected-rows" style="margin: 10px; " *ngIf="selectedDataStringPresentation">
Не використовуй style (хіба дуже треба). Краще все тримай в класах

2021-11-04 17:27 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.html
> +        </section>
Оця бокова панель повинна бути окремим компонентом. Ти її в багатьох місцях використовуєш. І в дашбордах (хоча вона там нічого і не робить) і тут в таблиці

2021-11-04 17:42 UTC, Olia1406 commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/rank-sheets.component.ts
> +    this.rankSheetList = this.dataService.rankSheetList;
щоб скопіювати мені треба використовувати якусь бібліотеку, чи можна просто newArr = [...arr]?, бо інуює deep i shallow копіювання , а тут масив з об'єктів, які теж містять об'єкти, то мабуть треба deep clone якийсь, так?

2021-11-04 17:47 UTC, Olia1406 commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/rank-sheets.component.html
> +          </ng-container>
ти вже то казав, а я знову так написала .., ок, може вже буду пам'ятати..)

2021-11-04 17:53 UTC, Olia1406 commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +  @ViewChild("agGrid", { static: false }) agGrid: AgGridAngular | any;
англар 12 потребує ініціалізації змінної зразу, інакше видає помилку, а як зініціалізувати то не знаю, є ще можливість відключити ту вимогу в tsconfig.json. Коли там пишу any, то помилки нема. Хіба написати =null

2021-11-04 17:54 UTC, Olia1406 commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +  selectedDataStringPresentation: string = '';
угум, ок)

2021-11-04 17:56 UTC, Olia1406 commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +  rankSheetData: any;
та , то шось лень взяла гору, думала шо то не так важливо

2021-11-04 17:59 UTC, Olia1406 commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +    return `rgb(${o(r() * s)}, ${o(r() * s)}, ${o(r() * s)})`;
ти маєш на увазі що треба константам?

2021-11-04 17:59 UTC, Olia1406 commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +    return `rgb(${o(r() * s)}, ${o(r() * s)}, ${o(r() * s)})`;
не дуже зрозуміла питання, але то просто для коротшого запису

2021-11-04 18:08 UTC, Olia1406 commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.html
> +        </section>
але ті бокові панелі трохи відрізняються, в них різна кількість секцій, різні дані, назви (це ше можна передати),але можуть дропдауни тоже бути інші і тут нема деяких штук які були там, карще показати це на дзвінку

2021-11-04 18:13 UTC, Olia1406 commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.html
> +    <div class="selected-rows" style="margin: 10px; " *ngIf="selectedDataStringPresentation">
ok

2021-11-05 16:52 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/rank-sheets.component.ts
> +    this.rankSheetList = this.dataService.rankSheetList;
тут я так подумав, що може і shallow підійти, бо тобі головне масив залишити цілісним
об'єкти ти не мала би змінювати

2021-11-05 16:52 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +  @ViewChild("agGrid", { static: false }) agGrid: AgGridAngular | any;
напиши null. Міняти тип не сильно вихід)

2021-11-05 16:54 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +    return `rgb(${o(r() * s)}, ${o(r() * s)}, ${o(r() * s)})`;
таке не треба робити, бо ти просто створюєш лишні змінні і займаєш пам'ять. Нічого не станеться, якщо запис буде довшим

2021-11-12 08:31 UTC, nazarb-eagle commented on projects/studio-sheets/src/app/pages/my-content/rank-sheets/default-rank-sheet/default-rank-sheet.component.ts
> +        ))
тут можна ще простіше зробити
`this.rowData = this.clonedRowData.filter(((row: MobiusData) => {
              let result = true;
              for (const key in dropdownValues) {
                if(dropdownValues.hasOwnProperty(key) && row.hasOwnProperty(key)) {
                  result &&= row[key] === dropdownValues[key] || !dropdownValues[key];
                }
              }
              return result;
            }
        ));`
Так в тебе код буде гнучкий, якщо добвляться нові фільтри чи зміняться колонки.
Це є один з принципів SOLID, що я казав тобі подивитися. Open Closed Principle - код повинен бути закритим для змін (як в тебе тут виходить, якщо зміняться фільтри, треба код переписувати), але відкритим для розширення (оце вже так як я написав)

2021-11-12 11:06 UTC, merged